# Generated by Django 4.2.30 on 2026-05-29 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('curso', models.CharField(max_length=100)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CRIADA', 'Criada'), ('EM_VALIDACAO', 'Em Validação'), ('CORRECAO_NECESSARIA', 'Correção Necessária'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('ENCAMINHADA', 'Encaminhada')], default='CRIADA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='estagios.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizacaoParceira',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('status_validacao', models.CharField(default='Pendente', max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estagios.solicitacao')),
            ],
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CORRECAO_NECESSARIA', 'Correção Necessária')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises', to='estagios.coordenador')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='estagios.solicitacao')),
            ],
        ),
    ]
