# Generated by Django 6.0.5 on 2026-06-02 00:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completo', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('arquivo', models.FileField(upload_to='documentos_estagio/')),
                ('status_validacao', models.CharField(default='Pendente', max_length=50)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ModeloDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo_template', models.FileField(blank=True, null=True, upload_to='modelos_documento/')),
                ('obrigatorio', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_empresa', models.BooleanField(default=False, verbose_name='Empresa')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('curso', models.CharField(max_length=100)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('setor', models.CharField(max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_assinatura', models.CharField(max_length=256)),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('valida', models.BooleanField(default=True)),
                ('assinante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='estagios.documento')),
            ],
            options={
                'ordering': ['-data_assinatura'],
            },
        ),
        migrations.CreateModel(
            name='ItemChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estagios.checklist')),
                ('modelo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_checklist', to='estagios.modelodocumento')),
            ],
            options={
                'unique_together': {('checklist', 'modelo_documento')},
            },
        ),
        migrations.AddField(
            model_name='checklist',
            name='modelo_documento',
            field=models.ManyToManyField(related_name='checklists', through='estagios.ItemChecklist', to='estagios.modelodocumento'),
        ),
        migrations.CreateModel(
            name='OrganizacaoParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('CRIADA', 'Criada'), ('EM_VALIDACAO', 'Em Validação'), ('CORRECAO_NECESSARIA', 'Correção Necessária'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('ENCAMINHADA', 'Encaminhada')], default='CRIADA', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='estagios.aluno')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('SOLICITACAO_CRIADA', 'Solicitação Criada'), ('DOCUMENTO_ENVIADO', 'Documento Enviado'), ('ANALISE_CONCLUIDA', 'Análise Concluída'), ('CORRECAO_SOLICITADA', 'Correção Solicitada'), ('SOLICITACAO_APROVADA', 'Solicitação Aprovada'), ('SOLICITACAO_REPROVADA', 'Solicitação Reprovada'), ('ENCAMINHAMENTO_REALIZADO', 'Encaminhamento Realizado')], max_length=30)),
                ('mensagem', models.TextField()),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('solicitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to='estagios.solicitacao')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data_encaminhamento', models.DateTimeField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaminhamentos', to='estagios.coordenador')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='estagios.organizacaoparceira')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos', to='estagios.solicitacao')),
            ],
            options={
                'ordering': ['-data_encaminhamento'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='solicitacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='estagios.solicitacao'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='solicitacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='estagios.solicitacao'),
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('CORRECAO_NECESSARIA', 'Correção Necessária')], max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('coordenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises', to='estagios.coordenador')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analise', to='estagios.solicitacao')),
            ],
            options={
                'ordering': ['-data_analise'],
            },
        ),
    ]
