# Generated by Django 4.2.30 on 2026-06-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('CRIADA', 'Criada'), ('EM_VALIDACAO', 'Em Validação'), ('CORRECAO_NECESSARIA', 'Correção Necessária'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada'), ('ENCAMINHADA', 'Encaminhada'), ('CONCLUIDA', 'Concluída')], default='CRIADA', max_length=20),
        ),
    ]
